---
version: '3.8'
services:
  db:
    restart: always
    # image: postgres:16-alpine
    build: ./.docker/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
      # - POSTGRES_MULTIPLE_DATABASES=auth_db,auth_usr,auth_pwd:main_db,main_usr,main_pwd
    ports: [5432:5432]
    networks: [project_name]
    volumes: [api_postgres_data:/var/lib/postgresql/data:rw]
    healthcheck:
      test: [CMD-SHELL, pg_isready, -d, zitadel, -U, postgres]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
networks:
  project_name:
volumes:
  api_postgres_data:
